# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGwtrm2gSaT6A9UJ_mcmcdSNDUG0aeZ_
"""

import streamlit as st
st.title("Hello, Sujitha!")
st.subheader("This is my first Streamlit app")
st.write("streamlit makes it easy to build web appsimport streamlit")
